- generic [active] [ref=e1]:
  - banner [ref=e2]:
    - generic [ref=e3]:
      - link "ysf.shoop" [ref=e4] [cursor=pointer]:
        - /url: /
      - navigation [ref=e5]:
        - link "Shop" [ref=e6] [cursor=pointer]:
          - /url: /shop
        - link "Watches" [ref=e7] [cursor=pointer]:
          - /url: /category/watches
        - link "Glasses" [ref=e8] [cursor=pointer]:
          - /url: /category/glasses
        - link "Cart" [ref=e9] [cursor=pointer]:
          - /url: /cart
  - main [ref=e10]:
    - generic [ref=e11]:
      - heading "Shop" [level=1] [ref=e12]
      - link "All" [ref=e14] [cursor=pointer]:
        - /url: /shop
      - generic [ref=e15]:
        - paragraph [ref=e16]: 0 products
        - generic [ref=e17]:
          - link "Newest" [ref=e18] [cursor=pointer]:
            - /url: "?sort=newest"
          - 'link "Price: Low" [ref=e19] [cursor=pointer]':
            - /url: "?sort=price_asc"
          - 'link "Price: High" [ref=e20] [cursor=pointer]':
            - /url: "?sort=price_desc"
      - paragraph [ref=e21]: No products found.
  - contentinfo [ref=e22]:
    - generic [ref=e23]:
      - generic [ref=e24]:
        - generic [ref=e25]:
          - heading "ysf.shoop" [level=3] [ref=e26]
          - paragraph [ref=e27]: Premium watches and glasses curated for style and precision.
        - generic [ref=e28]:
          - heading "Links" [level=3] [ref=e29]
          - list [ref=e30]:
            - listitem [ref=e31]:
              - link "All Products" [ref=e32] [cursor=pointer]:
                - /url: /shop
            - listitem [ref=e33]:
              - link "Watches" [ref=e34] [cursor=pointer]:
                - /url: /category/watches
            - listitem [ref=e35]:
              - link "Glasses" [ref=e36] [cursor=pointer]:
                - /url: /category/glasses
        - generic [ref=e37]:
          - heading "Support" [level=3] [ref=e38]
          - list [ref=e39]:
            - listitem [ref=e40]:
              - link "My Account" [ref=e41] [cursor=pointer]:
                - /url: /account
            - listitem [ref=e42]:
              - link "Order Tracking" [ref=e43] [cursor=pointer]:
                - /url: /account/orders
      - generic [ref=e44]: © 2026 ysf.shoop. All rights reserved.
  - button "Open Next.js Dev Tools" [ref=e50] [cursor=pointer]:
    - img [ref=e51]
  - alert [ref=e54]